#!/bin/bash 
#$ -pe smp 32
#$ -N Agat
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$-l h=!(compute-0-13)
#$ -o Agat-stdo.output
#$ -e Agat-stderr.output

##################Pre-Trandescoder##################

# 1o passo
grep '^>' Trinity_NCont_Clusters.fasta | sed 's/>//g' | awk -F'\t' '{OFS="\t"; $2 = $1; print}' | awk 'BEGIN{FS=OFS="\t"} {sub(/_.*/, "", $2); print}' | awk 'BEGIN{FS=OFS="\t"} {gsub(/[-.]/, "_", $2); print}' | sort -t$'\t' -k2,2 > Annotation_1line.gff3 #Dictionary of correspondence OldHeadrs/NewHeaders 

awk 'BEGIN{FS=OFS="\t"} NR==FNR{map[$1]=$2; next} /^>/{header=$0; gsub(/^>/, "", header); if(map[header]) print ">" map[header]; else print; next} {print}' Annotation_1line.gff3 Trinity_NCont_Clusters.fasta > Trinity_NCont_Clusters_C.fasta

grep '^>' Trinity_NCont_Clusters_C.fasta > Trinity_NCont_Clusters_C_Headers.txt

mv Trinity_NCont_Clusters.fasta ./00-Aux
mv Annotation_1line.gff3 ./00-Aux
mv Trinity_NCont_Clusters_C_Headers.txt ./00-Aux
mv Trinity_NCont_Clusters_C.fasta Trinity_NCont_Clusters.fasta

# 2o passo
./fastasplit -f ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep -c 5 -o ./Trinity_NCont_Clusters.fasta.transdecoder_dir

mv ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep_chunk_0000000 longest_orfs_00.fa
mv ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep_chunk_0000001 longest_orfs_01.fa
mv ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep_chunk_0000002 longest_orfs_02.fa
mv ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep_chunk_0000003 longest_orfs_03.fa
mv ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep_chunk_0000004 longest_orfs_04.fa

cp ./Trinity_NCont_Clusters.fasta.transdecoder_dir/longest_orfs.pep longest_orfs.pep

#Run Blast_Tdc Script
#Run Pfam_Tdc_Script
