#!/bin/bash 
#$ -pe smp 32
#$ -N BuscoMet_All
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -l h=!(compute-0-13)
#$ -o BuscoMet_All.output
#$ -e BuscoMet_All.output

singularity exec /share/apps/singularity/busco.v5.5.0.simg busco -i Trinity_All.fasta -o BuscoMet_SC -l /share/data03/dsimoes/Gammaruslocusta/RNASeq/01-Glocusta_RNASeq/02-Assembly/04-Buscos/metazoa_odb10 -m tran --offline -c 30 1>BuscoMet_All.log 2>BuscoMet_All.err

exit
