#!/bin/bash
#$ -pe smp 32
#$ -N Trans
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -l hostname=!(compute-0-11)
#$ -o Trans.output
#$ -e Trans.output

# Trinity_C
/home/dsimoes/DATA03/dsimoes/Gammaruslocusta/RNASeq/01-Glocusta_RNASeq/02-Assembly/03-Stats/transrate/transrate --assembly Trinity_C.fasta --output ./transrate_C_v0 --threads 30 1>trate_C_v0.log 2>trate_C_v0.err

# Trinity_All
#/home/dsimoes/DATA03/dsimoes/Gammaruslocusta/RNASeq/01-Glocusta_RNASeq/02-Assembly/03-Stats/transrate/transrate --assembly Trinity_All.fasta --output ./transrate_All_v0 --threads 30 1>trate_All_v0.log 2>trate_All_v0.err

exit

