#!/bin/bash
#$ -pe smp 32
#$ -N Trans
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -l hostname=!(compute-0-11)
#$ -o Trans.output
#$ -e Trans.output

# Carregar o módulo Singularity se necessário
# module load singularity  # Descomente esta linha se o seu cluster exigir

# Mostrar hora de início
echo "Início do job: $(date)"

# Correr Transrate dentro do container Singularity
singularity exec \
  -B /DATA03/dsimoes/Gammaruslocusta/RNASeq/01-Glocusta_RNASeq/02-Assembly/03-Stats:/mnt \
  /share/apps/singularity/transrate.simg \
  transrate --assembly /mnt/Trinity_C.fasta \
            --output /mnt/transrate_C_v0 \
            --threads 30 \
            1>/mnt/trate_C_v0.log \
            2>/mnt/trate_C_v0.err
echo "Fim do job: $(date)"
exit

