#!/bin/bash 
#$ -pe smp 32
#$ -N Rcorr
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -l hostname=!(compute-0-13)
#$ -o Rcorr-stdo.output
#$ -e Rcorr-stderr.output

# Início do tempo total
start_total=$(date +%s)

# Loop sobre os arquivos pareados gerados pelo Trimmomatic
for i in `ls -1 *_paired_1.fq.gz | sed 's/_paired_1.fq.gz//'`; do
    echo "Processando ${i}..."
    
    # Início do tempo por amostra
    start_sample=$(date +%s)
    
    singularity exec /share/apps/singularity/orca-6.simg run_rcorrector.pl \
        -t 30 \
        -1 ${i}_paired_1.fq.gz \
        -2 ${i}_paired_2.fq.gz
    
    # Fim do tempo por amostra
    end_sample=$(date +%s)
    duration_sample=$((end_sample - start_sample))
    echo "Amostra ${i} processada em ${duration_sample} segundos."
done

# Fim do tempo total
end_total=$(date +%s)
duration_total=$((end_total - start_total))

echo "Correção concluída! Tempo total: ${duration_total} segundos."
exit
